spring:
  application:
    name: multi-empresa

  datasource:
    url: jdbc:mysql://31.97.133.166:3306/multi_empresa
    username: user-multiempresa
    password: SecretoMulti2026.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 30
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  jackson:
    time-zone: America/Lima

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 30MB

server:
  port: 8093
  tomcat:
    max-http-form-post-size: -1
    max-part-count: -1

jwt:
  secret:
    key: 6EAB10E2B4F3AASDG912F9C32C73F0AH41J21A9F5FCE3C423F6D489E7BA84DA82

custom:
  server:
    hostname: https://api.multi-empresa.website

sunat:
  url: https://e-fact.facturacion-idmhperu.website/facturador/sunat/comprobante/sent
  url-guia: https://e-fact.facturacion-idmhperu.website/facturador/sunat/guia/sent
  url-guia-valid: https://e-fact.facturacion-idmhperu.website/facturador/sunat/guia/valid

google:
  drive:
    tokens-directory: /opt/multi-empresa/tokens

drive:
  folder-id:
    boletas: 1SqIv1mT_aDgGVno06mnG1ETbIJlPJIOy
    facturas: 1gmntNspgn1ATpT2qGI8-7Qyutv68KFgv
    notas: 1PAS67lMw7CiwcGL56vPgwet36XyYxeO7
    guias: 1gLEZa9eTo8IgHCu6zWCR5egpLcl8LCL8
    pagos: 1EwaDUz4iG1yqGARk6AC9fQ7BPaYm96jh
    productos-imagenes: 1Bp-UlXfLev0asfJYrf_4CakyYDrGw4Oo
    productos-fichas: 14qWmlircO0bE7qnXJfmUAmSD9LFj6fuz
    servicios-imagenes: 16bCKVsHWm0oa9D-2UeQg4dy9CkVFXClL
    servicios-fichas: 1U6MRsgdK3YI6cwApveioVTi1Xg9X6VIO
    logos: 1jKpoP8ofVfOXlDu77irFz-g4Qtn0PdyR
