spring:
  application:
    name: multi-empresa

  datasource:
    url: jdbc:mysql://31.97.133.166:3306/multi_empresa_test
    username: user-idmhperu
    password: Secretoidmh2026.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 30
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  jackson:
    time-zone: America/Lima

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8092

jwt:
  secret:
    key: 6EAB10E2B4F3AASDG912F9C32C73F0AH41J21A9F5FCE3C423F6D489E7BA84DA82

custom:
  server:
    hostname: https://api-dev.facturador.website

sunat:
  url: https://e-fact.facturacion-idmhperu.website/facturador/sunat/comprobante/sent
  url-guia: https://e-fact.facturacion-idmhperu.website/facturador/sunat/guia/sent
  url-guia-valid: https://e-fact.facturacion-idmhperu.website/facturador/sunat/guia/valid

drive:
  folder-id:
    boletas: 1Zw0IpAhvUpdCl2vFT9nHGdr35rskXInf
    facturas: 1Z9CDff4ilhJ-RsHwAnKRUi2zmihXHqGA
    notas: 1Loa34bdKO-iZeslVFJUgphV_we_eho6Y
    guias: 1RpdHBZzd1ItpNJq84d74RT4dupq6CvX4
    pagos: 1-sTd0S5IH8P32pI87a1BF5gf0BxgkZhq
    productos-imagenes: 1EwAWfL5YZzK2RwXnNgsLm2CSz8-LPZRa
    productos-fichas: 1IqmaWkVAi8uh71S8VdUO7EQBWMBFNIw6
    servicios-imagenes: 1MN0UEr7yYRoga_-3gM1nyj_d68IYHqrF
    servicios-fichas: 1fEDaQBIQGTxvbg7S_BwwjWwhxzy2ErFd
