-- ============================================================
-- V044: Add missing audit columns (updated_at/by, deleted_at/by)
--   Uses INFORMATION_SCHEMA conditional checks — safe to re-run.
--   person_type/unit_measure/charge_unit/payment_method may already
--   have columns from the partial previous run; all others checked too.
-- ============================================================

-- ─── Macro pattern (per column per table): ────────────────
--   SET @s = (SELECT IF(COUNT(*)=0, 'ALTER TABLE t ADD COLUMN c ...', 'SELECT 1')
--             FROM INFORMATION_SCHEMA.COLUMNS
--             WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t' AND COLUMN_NAME='c');
--   PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
-- ──────────────────────────────────────────────────────────

-- ─── person_type ──────────────────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE person_type ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='person_type' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE person_type ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='person_type' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE person_type ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='person_type' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE person_type ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='person_type' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;

-- ─── unit_measure ─────────────────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE unit_measure ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='unit_measure' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE unit_measure ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='unit_measure' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE unit_measure ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='unit_measure' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE unit_measure ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='unit_measure' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;

-- ─── charge_unit ──────────────────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE charge_unit ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='charge_unit' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE charge_unit ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='charge_unit' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE charge_unit ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='charge_unit' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE charge_unit ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='charge_unit' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;

-- ─── payment_method ───────────────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE payment_method ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='payment_method' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE payment_method ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='payment_method' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE payment_method ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='payment_method' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE payment_method ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='payment_method' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;

-- ─── sale_item ────────────────────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_item ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_item' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_item ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_item' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_item ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_item' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_item ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_item' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;

-- ─── sale_payment ─────────────────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_payment ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_payment' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_payment ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_payment' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_payment ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_payment' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_payment ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_payment' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;

-- ─── sale_installment ─────────────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_installment ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_installment' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_installment ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_installment' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_installment ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_installment' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE sale_installment ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sale_installment' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;

-- ─── credit_debit_note_type ───────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE credit_debit_note_type ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='credit_debit_note_type' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE credit_debit_note_type ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='credit_debit_note_type' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE credit_debit_note_type ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='credit_debit_note_type' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE credit_debit_note_type ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='credit_debit_note_type' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;

-- ─── credit_debit_note_item ───────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE credit_debit_note_item ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='credit_debit_note_item' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE credit_debit_note_item ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='credit_debit_note_item' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE credit_debit_note_item ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='credit_debit_note_item' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE credit_debit_note_item ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='credit_debit_note_item' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;

-- ─── carrier ──────────────────────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE carrier ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='carrier' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE carrier ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='carrier' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE carrier ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='carrier' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE carrier ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='carrier' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;

-- ─── driver ───────────────────────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE driver ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='driver' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE driver ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='driver' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE driver ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='driver' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE driver ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='driver' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;

-- ─── driver_vehicle ───────────────────────────────────────
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE driver_vehicle ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='driver_vehicle' AND COLUMN_NAME='updated_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE driver_vehicle ADD COLUMN updated_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='driver_vehicle' AND COLUMN_NAME='updated_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE driver_vehicle ADD COLUMN deleted_at DATETIME DEFAULT NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='driver_vehicle' AND COLUMN_NAME='deleted_at');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE driver_vehicle ADD COLUMN deleted_by VARCHAR(50) NULL','SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='driver_vehicle' AND COLUMN_NAME='deleted_by');
PREPARE p FROM @s; EXECUTE p; DEALLOCATE PREPARE p;
