ALTER TABLE document_type_sunat
    ADD COLUMN updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN updated_by VARCHAR(50) NULL,
    ADD COLUMN deleted_at DATETIME DEFAULT NULL,
    ADD COLUMN deleted_by VARCHAR(50) NULL;
